-- Données de test pour le questionnaire
-- Exécutez ce SQL dans le SQL Editor de Supabase

INSERT INTO questionnaire_responses (nickname, score, total_questions, percentage, internal_score, answers, created_at) VALUES
-- Top performers (scores internes élevés)
('SpeedyGonzalez', 5, 5, 100, 498, '[{"question":"Quelle est la capitale de la France ?","userAnswer":"Paris","correctAnswer":"Paris","isCorrect":true},{"question":"Combien de continents y a-t-il sur Terre ?","userAnswer":"7","correctAnswer":"7","isCorrect":true},{"question":"Quel est le plus grand océan du monde ?","userAnswer":"Pacifique","correctAnswer":"Pacifique","isCorrect":true},{"question":"En quelle année a eu lieu la Révolution française ?","userAnswer":"1789","correctAnswer":"1789","isCorrect":true},{"question":"Quel est l''élément chimique avec le symbole ''O'' ?","userAnswer":"Oxygène","correctAnswer":"Oxygène","isCorrect":true}]', NOW() - INTERVAL '1 hour'),

('Flash', 5, 5, 100, 485, '[{"question":"Quelle est la capitale de la France ?","userAnswer":"Paris","correctAnswer":"Paris","isCorrect":true},{"question":"Combien de continents y a-t-il sur Terre ?","userAnswer":"7","correctAnswer":"7","isCorrect":true},{"question":"Quel est le plus grand océan du monde ?","userAnswer":"Pacifique","correctAnswer":"Pacifique","isCorrect":true},{"question":"En quelle année a eu lieu la Révolution française ?","userAnswer":"1789","correctAnswer":"1789","isCorrect":true},{"question":"Quel est l''élément chimique avec le symbole ''O'' ?","userAnswer":"Oxygène","correctAnswer":"Oxygène","isCorrect":true}]', NOW() - INTERVAL '2 hours'),

('Lightning', 5, 5, 100, 472, '[{"question":"Quelle est la capitale de la France ?","userAnswer":"Paris","correctAnswer":"Paris","isCorrect":true},{"question":"Combien de continents y a-t-il sur Terre ?","userAnswer":"7","correctAnswer":"7","isCorrect":true},{"question":"Quel est le plus grand océan du monde ?","userAnswer":"Pacifique","correctAnswer":"Pacifique","isCorrect":true},{"question":"En quelle année a eu lieu la Révolution française ?","userAnswer":"1789","correctAnswer":"1789","isCorrect":true},{"question":"Quel est l''élément chimique avec le symbole ''O'' ?","userAnswer":"Oxygène","correctAnswer":"Oxygène","isCorrect":true}]', NOW() - INTERVAL '3 hours'),

-- Good performers
('SmartCookie', 4, 5, 80, 380, '[{"question":"Quelle est la capitale de la France ?","userAnswer":"Paris","correctAnswer":"Paris","isCorrect":true},{"question":"Combien de continents y a-t-il sur Terre ?","userAnswer":"7","correctAnswer":"7","isCorrect":true},{"question":"Quel est le plus grand océan du monde ?","userAnswer":"Pacifique","correctAnswer":"Pacifique","isCorrect":true},{"question":"En quelle année a eu lieu la Révolution française ?","userAnswer":"1789","correctAnswer":"1789","isCorrect":true},{"question":"Quel est l''élément chimique avec le symbole ''O'' ?","userAnswer":"Or","correctAnswer":"Oxygène","isCorrect":false}]', NOW() - INTERVAL '4 hours'),

('Brainiac', 4, 5, 80, 365, '[{"question":"Quelle est la capitale de la France ?","userAnswer":"Paris","correctAnswer":"Paris","isCorrect":true},{"question":"Combien de continents y a-t-il sur Terre ?","userAnswer":"7","correctAnswer":"7","isCorrect":true},{"question":"Quel est le plus grand océan du monde ?","userAnswer":"Pacifique","correctAnswer":"Pacifique","isCorrect":true},{"question":"En quelle année a eu lieu la Révolution française ?","userAnswer":"1776","correctAnswer":"1789","isCorrect":false},{"question":"Quel est l''élément chimique avec le symbole ''O'' ?","userAnswer":"Oxygène","correctAnswer":"Oxygène","isCorrect":true}]', NOW() - INTERVAL '5 hours'),

('Einstein', 4, 5, 80, 350, '[{"question":"Quelle est la capitale de la France ?","userAnswer":"Paris","correctAnswer":"Paris","isCorrect":true},{"question":"Combien de continents y a-t-il sur Terre ?","userAnswer":"6","correctAnswer":"7","isCorrect":false},{"question":"Quel est le plus grand océan du monde ?","userAnswer":"Pacifique","correctAnswer":"Pacifique","isCorrect":true},{"question":"En quelle année a eu lieu la Révolution française ?","userAnswer":"1789","correctAnswer":"1789","isCorrect":true},{"question":"Quel est l''élément chimique avec le symbole ''O'' ?","userAnswer":"Oxygène","correctAnswer":"Oxygène","isCorrect":true}]', NOW() - INTERVAL '6 hours'),

-- Average performers
('AverageJoe', 3, 5, 60, 280, '[{"question":"Quelle est la capitale de la France ?","userAnswer":"Paris","correctAnswer":"Paris","isCorrect":true},{"question":"Combien de continents y a-t-il sur Terre ?","userAnswer":"7","correctAnswer":"7","isCorrect":true},{"question":"Quel est le plus grand océan du monde ?","userAnswer":"Atlantique","correctAnswer":"Pacifique","isCorrect":false},{"question":"En quelle année a eu lieu la Révolution française ?","userAnswer":"1789","correctAnswer":"1789","isCorrect":true},{"question":"Quel est l''élément chimique avec le symbole ''O'' ?","userAnswer":"Or","correctAnswer":"Oxygène","isCorrect":false}]', NOW() - INTERVAL '7 hours'),

('MediocreMike', 3, 5, 60, 265, '[{"question":"Quelle est la capitale de la France ?","userAnswer":"Londres","correctAnswer":"Paris","isCorrect":false},{"question":"Combien de continents y a-t-il sur Terre ?","userAnswer":"7","correctAnswer":"7","isCorrect":true},{"question":"Quel est le plus grand océan du monde ?","userAnswer":"Pacifique","correctAnswer":"Pacifique","isCorrect":true},{"question":"En quelle année a eu lieu la Révolution française ?","userAnswer":"1789","correctAnswer":"1789","isCorrect":true},{"question":"Quel est l''élément chimique avec le symbole ''O'' ?","userAnswer":"Osmium","correctAnswer":"Oxygène","isCorrect":false}]', NOW() - INTERVAL '8 hours'),

('SoSoSophie', 3, 5, 60, 250, '[{"question":"Quelle est la capitale de la France ?","userAnswer":"Paris","correctAnswer":"Paris","isCorrect":true},{"question":"Combien de continents y a-t-il sur Terre ?","userAnswer":"5","correctAnswer":"7","isCorrect":false},{"question":"Quel est le plus grand océan du monde ?","userAnswer":"Pacifique","correctAnswer":"Pacifique","isCorrect":true},{"question":"En quelle année a eu lieu la Révolution française ?","userAnswer":"1804","correctAnswer":"1789","isCorrect":false},{"question":"Quel est l''élément chimique avec le symbole ''O'' ?","userAnswer":"Oxygène","correctAnswer":"Oxygène","isCorrect":true}]', NOW() - INTERVAL '9 hours'),

-- Poor performers
('SlowPoke', 2, 5, 40, 180, '[{"question":"Quelle est la capitale de la France ?","userAnswer":"Paris","correctAnswer":"Paris","isCorrect":true},{"question":"Combien de continents y a-t-il sur Terre ?","userAnswer":"5","correctAnswer":"7","isCorrect":false},{"question":"Quel est le plus grand océan du monde ?","userAnswer":"Atlantique","correctAnswer":"Pacifique","isCorrect":false},{"question":"En quelle année a eu lieu la Révolution française ?","userAnswer":"1789","correctAnswer":"1789","isCorrect":true},{"question":"Quel est l''élément chimique avec le symbole ''O'' ?","userAnswer":"Or","correctAnswer":"Oxygène","isCorrect":false}]', NOW() - INTERVAL '10 hours'),

('ConfusedCarl', 2, 5, 40, 165, '[{"question":"Quelle est la capitale de la France ?","userAnswer":"Berlin","correctAnswer":"Paris","isCorrect":false},{"question":"Combien de continents y a-t-il sur Terre ?","userAnswer":"7","correctAnswer":"7","isCorrect":true},{"question":"Quel est le plus grand océan du monde ?","userAnswer":"Indien","correctAnswer":"Pacifique","isCorrect":false},{"question":"En quelle année a eu lieu la Révolution française ?","userAnswer":"1815","correctAnswer":"1789","isCorrect":false},{"question":"Quel est l''élément chimique avec le symbole ''O'' ?","userAnswer":"Oxygène","correctAnswer":"Oxygène","isCorrect":true}]', NOW() - INTERVAL '11 hours'),

('LostLinda', 2, 5, 40, 150, '[{"question":"Quelle est la capitale de la France ?","userAnswer":"Paris","correctAnswer":"Paris","isCorrect":true},{"question":"Combien de continents y a-t-il sur Terre ?","userAnswer":"8","correctAnswer":"7","isCorrect":false},{"question":"Quel est le plus grand océan du monde ?","userAnswer":"Arctique","correctAnswer":"Pacifique","isCorrect":false},{"question":"En quelle année a eu lieu la Révolution française ?","userAnswer":"1789","correctAnswer":"1789","isCorrect":true},{"question":"Quel est l''élément chimique avec le symbole ''O'' ?","userAnswer":"Olive","correctAnswer":"Oxygène","isCorrect":false}]', NOW() - INTERVAL '12 hours'),

-- Very poor performers (flop 3)
('CluelessChris', 1, 5, 20, 95, '[{"question":"Quelle est la capitale de la France ?","userAnswer":"Londres","correctAnswer":"Paris","isCorrect":false},{"question":"Combien de continents y a-t-il sur Terre ?","userAnswer":"5","correctAnswer":"7","isCorrect":false},{"question":"Quel est le plus grand océan du monde ?","userAnswer":"Atlantique","correctAnswer":"Pacifique","isCorrect":false},{"question":"En quelle année a eu lieu la Révolution française ?","userAnswer":"1789","correctAnswer":"1789","isCorrect":true},{"question":"Quel est l''élément chimique avec le symbole ''O'' ?","userAnswer":"Or","correctAnswer":"Oxygène","isCorrect":false}]', NOW() - INTERVAL '13 hours'),

('RandomRandy', 1, 5, 20, 80, '[{"question":"Quelle est la capitale de la France ?","userAnswer":"Madrid","correctAnswer":"Paris","isCorrect":false},{"question":"Combien de continents y a-t-il sur Terre ?","userAnswer":"6","correctAnswer":"7","isCorrect":false},{"question":"Quel est le plus grand océan du monde ?","userAnswer":"Indien","correctAnswer":"Pacifique","isCorrect":false},{"question":"En quelle année a eu lieu la Révolution française ?","userAnswer":"1804","correctAnswer":"1789","isCorrect":false},{"question":"Quel est l''élément chimique avec le symbole ''O'' ?","userAnswer":"Oxygène","correctAnswer":"Oxygène","isCorrect":true}]', NOW() - INTERVAL '14 hours'),

('GuessingGina', 1, 5, 20, 65, '[{"question":"Quelle est la capitale de la France ?","userAnswer":"Berlin","correctAnswer":"Paris","isCorrect":false},{"question":"Combien de continents y a-t-il sur Terre ?","userAnswer":"8","correctAnswer":"7","isCorrect":false},{"question":"Quel est le plus grand océan du monde ?","userAnswer":"Pacifique","correctAnswer":"Pacifique","isCorrect":true},{"question":"En quelle année a eu lieu la Révolution française ?","userAnswer":"1776","correctAnswer":"1789","isCorrect":false},{"question":"Quel est l''élément chimique avec le symbole ''O'' ?","userAnswer":"Osmium","correctAnswer":"Oxygène","isCorrect":false}]', NOW() - INTERVAL '15 hours'),

-- Zero score
('TotalFail', 0, 5, 0, 45, '[{"question":"Quelle est la capitale de la France ?","userAnswer":"Londres","correctAnswer":"Paris","isCorrect":false},{"question":"Combien de continents y a-t-il sur Terre ?","userAnswer":"5","correctAnswer":"7","isCorrect":false},{"question":"Quel est le plus grand océan du monde ?","userAnswer":"Atlantique","correctAnswer":"Pacifique","isCorrect":false},{"question":"En quelle année a eu lieu la Révolution française ?","userAnswer":"1776","correctAnswer":"1789","isCorrect":false},{"question":"Quel est l''élément chimique avec le symbole ''O'' ?","userAnswer":"Or","correctAnswer":"Oxygène","isCorrect":false}]', NOW() - INTERVAL '16 hours'),

('NoIdea', 0, 5, 0, 30, '[{"question":"Quelle est la capitale de la France ?","userAnswer":"Madrid","correctAnswer":"Paris","isCorrect":false},{"question":"Combien de continents y a-t-il sur Terre ?","userAnswer":"6","correctAnswer":"7","isCorrect":false},{"question":"Quel est le plus grand océan du monde ?","userAnswer":"Indien","correctAnswer":"Pacifique","isCorrect":false},{"question":"En quelle année a eu lieu la Révolution française ?","userAnswer":"1804","correctAnswer":"1789","isCorrect":false},{"question":"Quel est l''élément chimique avec le symbole ''O'' ?","userAnswer":"Osmium","correctAnswer":"Oxygène","isCorrect":false}]', NOW() - INTERVAL '17 hours');
